name: html_recipe_parser
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://codeberg.org/eggnog/html_recipe_parser

environment:
  sdk: ^3.1.5

dependencies:
  html: ^0.15.4
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
