name: html_recipe_parser
description: An HTML recipe parser for websites that adhere to schema.org's Recipe schema
version: 0.4.0
repository: https://github.com/eggnogdev/html_recipe_parser

environment:
  sdk: ^3.1.5

dependencies:
  html: ^0.15.4
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
