name: html_recipe_parser
description: HTML recipe parser for recipies following https://schema.org/Recipe
version: 0.0.1
homepage: https://codeberg.org/eggnog/html_recipe_parser

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  html: ^0.15.4
  http: ^1.1.0
